import type {
  PipelineStageDefinition,
  UnseenSession,
} from "./unseen-types";

export const DEMO_SESSION_ID = "unseen-demo-neon-district-0813";
export const DEMO_GENERATED_AT = "2026-08-05T18:30:00+08:00";

export const DEMO_PIPELINE: PipelineStageDefinition[] = [
  {
    id: "ingest",
    label: "Recordings secured",
    shortLabel: "Ingest",
    description: "Verified squad consent, media integrity, and voice permissions.",
    progress: 12,
    durationHintMs: 700,
  },
  {
    id: "align",
    label: "Perspectives synchronised",
    shortLabel: "Align",
    description: "Matched round timers, shared audio peaks, and kill-feed events.",
    progress: 30,
    durationHintMs: 850,
  },
  {
    id: "understand",
    label: "Session understood",
    shortLabel: "Understand",
    description: "Read the HUD, transcribed opted-in comms, and detected reactions.",
    progress: 56,
    durationHintMs: 950,
  },
  {
    id: "reconstruct",
    label: "Squad story reconstructed",
    shortLabel: "Reconstruct",
    description: "Connected actions and reactions across all three perspectives.",
    progress: 74,
    durationHintMs: 900,
  },
  {
    id: "direct",
    label: "Director's Cut assembled",
    shortLabel: "Direct",
    description: "Ranked moments and planned perspective switches, captions, and mix.",
    progress: 91,
    durationHintMs: 900,
  },
  {
    id: "ready",
    label: "Your unseen story is ready",
    shortLabel: "Ready",
    description: "Created the squad film, personal reveals, and grounded session Q&A.",
    progress: 100,
    durationHintMs: 500,
  },
];

export const DEMO_SESSION: UnseenSession = {
  id: DEMO_SESSION_ID,
  provenance: {
    kind: "synthetic_demo_fixture",
    disclosure:
      "This curated prototype session is entirely synthetic. Names, gameplay events, recordings, dialogue, scores, and AI outputs do not represent real players or a real match.",
    generatedBy: "Team UNSEEN",
    representsRealPlayers: false,
    containsRealGameplay: false,
    intendedUse: "Garena AI Build Challenge prototype demonstration",
  },
  title: "The Hold Nobody Saw",
  game: "Arena Strike",
  mode: "Ranked · First to 7",
  map: "Neon District",
  result: "victory",
  score: "7–6",
  playedAt: "2026-08-05T16:42:00+08:00",
  durationMs: 828_000,
  rounds: 13,
  focusParticipantId: "ace",
  participants: [
    {
      id: "ace",
      handle: "ACE.exe",
      displayName: "Ace",
      role: "duelist",
      character: "Kestrel",
      accent: "ember",
      avatarInitials: "AE",
      consent: {
        gameplayRecording: "granted",
        voiceChat: "granted",
        aiAnalysis: "granted",
        squadSharing: "granted",
        grantedAt: "2026-08-05T16:38:12+08:00",
        canRevoke: true,
      },
    },
    {
      id: "rin",
      handle: "RIN//lock",
      displayName: "Rin",
      role: "sentinel",
      character: "Ciphera",
      accent: "cyan",
      avatarInitials: "RL",
      consent: {
        gameplayRecording: "granted",
        voiceChat: "granted",
        aiAnalysis: "granted",
        squadSharing: "granted",
        grantedAt: "2026-08-05T16:38:44+08:00",
        canRevoke: true,
      },
    },
    {
      id: "miko",
      handle: "MIKO.jpg",
      displayName: "Miko",
      role: "support",
      character: "Lumen",
      accent: "violet",
      avatarInitials: "MJ",
      consent: {
        gameplayRecording: "granted",
        voiceChat: "granted",
        aiAnalysis: "granted",
        squadSharing: "granted",
        grantedAt: "2026-08-05T16:39:01+08:00",
        canRevoke: true,
      },
    },
  ],
  pipeline: DEMO_PIPELINE,
  sources: [
    {
      id: "src-ace",
      participantId: "ace",
      fileName: "ace_ranked_2026-08-05.mp4",
      durationMs: 828_000,
      alignmentOffsetMs: 0,
      alignmentConfidence: 0.99,
      resolution: "2560x1440",
      frameRate: 60,
      audio: { game: true, optedInVoice: true, sampleRateHz: 48000 },
      anchors: [
        {
          id: "anchor-ace-start",
          type: "round_start",
          sourceTimeMs: 615_000,
          masterTimeMs: 615_000,
          confidence: 0.99,
          label: "Round 13 barrier drop",
        },
        {
          id: "anchor-ace-feed",
          type: "kill_feed",
          sourceTimeMs: 686_400,
          masterTimeMs: 686_400,
          confidence: 0.98,
          label: "Rin stops second flanker",
        },
      ],
    },
    {
      id: "src-rin",
      participantId: "rin",
      fileName: "rin_neon_district.mkv",
      durationMs: 831_120,
      alignmentOffsetMs: -2_840,
      alignmentConfidence: 0.97,
      resolution: "1920x1080",
      frameRate: 60,
      audio: { game: true, optedInVoice: true, sampleRateHz: 48000 },
      anchors: [
        {
          id: "anchor-rin-start",
          type: "round_start",
          sourceTimeMs: 617_840,
          masterTimeMs: 615_000,
          confidence: 0.98,
          label: "Round 13 barrier drop",
        },
        {
          id: "anchor-rin-call",
          type: "shared_audio",
          sourceTimeMs: 686_290,
          masterTimeMs: 683_450,
          confidence: 0.96,
          label: "Two wrapping callout",
        },
      ],
    },
    {
      id: "src-miko",
      participantId: "miko",
      fileName: "miko_squad_capture.mp4",
      durationMs: 826_770,
      alignmentOffsetMs: 1_060,
      alignmentConfidence: 0.96,
      resolution: "1920x1080",
      frameRate: 60,
      audio: { game: true, optedInVoice: true, sampleRateHz: 48000 },
      anchors: [
        {
          id: "anchor-miko-laugh",
          type: "shared_audio",
          sourceTimeMs: 522_910,
          masterTimeMs: 523_970,
          confidence: 0.97,
          label: "Squad laughter peak in round 7",
        },
        {
          id: "anchor-miko-timer",
          type: "round_timer",
          sourceTimeMs: 690_010,
          masterTimeMs: 691_070,
          confidence: 0.95,
          label: "Round 13 HUD timer 0:18",
        },
      ],
    },
  ],
  evidence: [
    {
      id: "ev-r7-flash-throw",
      type: "visual_event",
      timestampMs: 520_900,
      endMs: 522_250,
      participantId: "miko",
      sourceId: "src-miko",
      label: "Utility rebounds off the door frame",
      detail:
        "Miko's flash clips a closing door and returns toward the squad instead of the site.",
      confidence: 0.96,
    },
    {
      id: "ev-r7-team-blind",
      type: "cross_perspective",
      timestampMs: 522_340,
      endMs: 524_100,
      label: "All three squad perspectives white out",
      detail:
        "The same flash detonation is visible in Ace, Rin, and Miko's aligned recordings.",
      confidence: 0.99,
    },
    {
      id: "ev-r7-miko-voice",
      type: "voice_transcript",
      timestampMs: 523_180,
      endMs: 525_400,
      participantId: "miko",
      sourceId: "src-miko",
      label: "Miko realises the mistake",
      detail: "Opted-in squad voice transcript.",
      quote: "That was meant for them. Nobody saw that, right?",
      confidence: 0.98,
    },
    {
      id: "ev-r7-laughter",
      type: "audio_reaction",
      timestampMs: 523_970,
      endMs: 528_500,
      label: "Squad laughter spikes",
      detail:
        "Overlapping laughter from all three voice tracks peaks 1.6 seconds after the team flash.",
      confidence: 0.97,
    },
    {
      id: "ev-r13-flank-hud",
      type: "hud_signal",
      timestampMs: 681_800,
      endMs: 683_100,
      participantId: "rin",
      sourceId: "src-rin",
      label: "Rin spots two enemies rotating behind the squad",
      detail:
        "Two silhouettes cross Rin's trip sensor while Ace and Miko continue toward A site.",
      confidence: 0.94,
    },
    {
      id: "ev-r13-rin-call",
      type: "voice_transcript",
      timestampMs: 683_450,
      endMs: 685_200,
      participantId: "rin",
      sourceId: "src-rin",
      label: "Rin tells the squad to keep moving",
      detail: "Opted-in squad voice transcript.",
      quote: "Two wrapping. Stay main — I've got it.",
      confidence: 0.99,
    },
    {
      id: "ev-r13-rin-hold",
      type: "visual_event",
      timestampMs: 684_900,
      endMs: 687_250,
      participantId: "rin",
      sourceId: "src-rin",
      label: "Rin stops the two-player flank alone",
      detail:
        "Rin delays both flankers, eliminates one, and leaves the second at critical health before falling.",
      confidence: 0.97,
    },
    {
      id: "ev-r13-feed",
      type: "hud_signal",
      timestampMs: 686_400,
      participantId: "ace",
      sourceId: "src-ace",
      label: "Ace's kill feed shows Rin's off-screen trade",
      detail:
        "The only clue in Ace's perspective is a 700 ms kill-feed update during the site entry.",
      confidence: 0.99,
    },
    {
      id: "ev-r13-miko-draw",
      type: "visual_event",
      timestampMs: 689_200,
      endMs: 693_100,
      participantId: "miko",
      sourceId: "src-miko",
      label: "Miko draws the defender's last utility",
      detail:
        "Miko steps into the crossfire, forces the defender to spend both charges, and creates Ace's route to cover.",
      confidence: 0.95,
    },
    {
      id: "ev-r13-miko-call",
      type: "voice_transcript",
      timestampMs: 690_050,
      endMs: 691_200,
      participantId: "miko",
      sourceId: "src-miko",
      label: "Miko calls the opening",
      detail: "Opted-in squad voice transcript.",
      quote: "Swing on me — last charge is gone.",
      confidence: 0.98,
    },
    {
      id: "ev-r13-ace-clutch",
      type: "visual_event",
      timestampMs: 694_100,
      endMs: 701_600,
      participantId: "ace",
      sourceId: "src-ace",
      label: "Ace converts the final 1v2",
      detail:
        "Ace uses the cover opened by Miko, isolates both defenders, and secures the 7–6 win.",
      confidence: 0.99,
    },
    {
      id: "ev-r13-reaction",
      type: "audio_reaction",
      timestampMs: 701_900,
      endMs: 705_800,
      label: "Squad celebration peaks",
      detail:
        "All three voice tracks overlap as the victory banner appears; Rin is loudest despite being eliminated.",
      confidence: 0.99,
    },
    {
      id: "ev-r10-save",
      type: "cross_perspective",
      timestampMs: 607_200,
      endMs: 611_500,
      participantId: "ace",
      sourceId: "src-ace",
      label: "Ace unknowingly dodges a sniper angle",
      detail:
        "Rin's smoke lands 140 ms before the shot crosses the angle on Ace's perspective.",
      confidence: 0.93,
    },
  ],
  incidents: [
    {
      id: "inc-r7-door-flash",
      category: "mistake",
      startMs: 520_900,
      endMs: 528_500,
      headline: "The flash that came back",
      summary:
        "A door-frame rebound blinds the entire squad, then turns into the loudest laugh of round seven.",
      participantIds: ["miko", "ace", "rin"],
      evidenceIds: [
        "ev-r7-flash-throw",
        "ev-r7-team-blind",
        "ev-r7-miko-voice",
        "ev-r7-laughter",
      ],
      gameplayImpact: 0.43,
      emotionalIntensity: 0.96,
      confidence: 0.97,
    },
    {
      id: "inc-r13-flank-hold",
      category: "teamwork",
      startMs: 681_800,
      endMs: 687_250,
      headline: "Rin holds the unseen flank",
      summary:
        "Rin quietly absorbs a two-player rotation so Ace and Miko can continue the final execute.",
      participantIds: ["rin", "ace", "miko"],
      evidenceIds: [
        "ev-r13-flank-hud",
        "ev-r13-rin-call",
        "ev-r13-rin-hold",
        "ev-r13-feed",
      ],
      gameplayImpact: 0.97,
      emotionalIntensity: 0.72,
      confidence: 0.97,
    },
    {
      id: "inc-r13-miko-sacrifice",
      category: "sacrifice",
      startMs: 689_200,
      endMs: 693_100,
      headline: "Miko spends a life to create the opening",
      summary:
        "Miko forces the last defensive utility out and calls the exact moment Ace can swing.",
      participantIds: ["miko", "ace"],
      evidenceIds: ["ev-r13-miko-draw", "ev-r13-miko-call"],
      gameplayImpact: 0.91,
      emotionalIntensity: 0.79,
      confidence: 0.96,
    },
    {
      id: "inc-r13-clutch",
      category: "clutch",
      startMs: 694_100,
      endMs: 705_800,
      headline: "Ace finishes the story",
      summary:
        "Ace wins the visible 1v2, but the aligned timeline reveals the two teammate plays that made it possible.",
      participantIds: ["ace", "rin", "miko"],
      evidenceIds: ["ev-r13-ace-clutch", "ev-r13-reaction"],
      gameplayImpact: 1,
      emotionalIntensity: 1,
      confidence: 0.99,
    },
    {
      id: "inc-r10-smoke-save",
      category: "setup",
      startMs: 607_200,
      endMs: 611_500,
      headline: "The smoke Ace never noticed",
      summary:
        "Rin's perfectly timed smoke blocks a lethal sniper shot less than a blink before it reaches Ace.",
      participantIds: ["rin", "ace"],
      evidenceIds: ["ev-r10-save"],
      gameplayImpact: 0.81,
      emotionalIntensity: 0.38,
      confidence: 0.93,
    },
  ],
  moments: [
    {
      id: "moment-unseen-hold",
      rank: 1,
      kind: "team_play",
      title: "The hold behind the clutch",
      startMs: 681_800,
      endMs: 705_800,
      summary:
        "Rin stops the flank, Miko drains the last utility, and Ace converts the opening — three perspectives, one winning play.",
      storyBeat: "Reveal the invisible setup before returning to the clutch everyone remembers.",
      participantIds: ["rin", "miko", "ace"],
      perspectiveOrder: ["ace", "rin", "miko", "ace"],
      evidenceIds: [
        "ev-r13-rin-call",
        "ev-r13-rin-hold",
        "ev-r13-miko-draw",
        "ev-r13-miko-call",
        "ev-r13-ace-clutch",
        "ev-r13-reaction",
      ],
      scores: {
        gameplay: 0.99,
        reaction: 0.96,
        novelty: 0.93,
        teamwork: 1,
        overall: 0.98,
      },
      tags: ["final round", "off-screen impact", "teamwork", "clutch"],
    },
    {
      id: "moment-round-seven",
      rank: 2,
      kind: "comedy",
      title: "Nobody saw that, right?",
      startMs: 520_900,
      endMs: 528_500,
      summary:
        "Miko's flash returns off a closing door, blinds all three players, and creates the session's biggest laugh.",
      storyBeat: "Give the recap a human reset before its final-round escalation.",
      participantIds: ["miko", "ace", "rin"],
      perspectiveOrder: ["miko", "ace", "rin"],
      evidenceIds: [
        "ev-r7-flash-throw",
        "ev-r7-team-blind",
        "ev-r7-miko-voice",
        "ev-r7-laughter",
      ],
      scores: {
        gameplay: 0.43,
        reaction: 0.98,
        novelty: 0.96,
        teamwork: 0.55,
        overall: 0.82,
      },
      tags: ["round 7", "mistake", "laughter", "voice reaction"],
    },
    {
      id: "moment-smoke-save",
      rank: 3,
      kind: "turning_point",
      title: "Saved by 140 milliseconds",
      startMs: 607_200,
      endMs: 611_500,
      summary:
        "A cross-perspective comparison shows Rin's smoke erase a lethal angle just before Ace peeks it.",
      storyBeat: "Foreshadow that the squad's smallest actions decide the largest moments.",
      participantIds: ["rin", "ace"],
      perspectiveOrder: ["ace", "rin"],
      evidenceIds: ["ev-r10-save"],
      scores: {
        gameplay: 0.81,
        reaction: 0.35,
        novelty: 0.89,
        teamwork: 0.9,
        overall: 0.76,
      },
      tags: ["timing", "save", "cross-perspective"],
    },
  ],
  directorCut: {
    id: "cut-neon-district-v1",
    title: "The Hold Nobody Saw",
    subtitle: "Three perspectives. One impossible final round.",
    durationMs: 79_000,
    status: "ready",
    aspectRatio: "16:9",
    quality: "1080p",
    editBeats: [
      {
        id: "beat-01",
        order: 1,
        momentId: "moment-unseen-hold",
        startMs: 694_100,
        endMs: 699_400,
        perspectiveId: "ace",
        transition: "hard_cut",
        caption: "FINAL ROUND · 1v2",
        narration: "This is the play Ace remembers.",
        audioFocus: "game",
      },
      {
        id: "beat-02",
        order: 2,
        momentId: "moment-round-seven",
        startMs: 520_900,
        endMs: 528_500,
        perspectiveId: "miko",
        transition: "dip_to_black",
        caption: "THREE ROUNDS EARLIER",
        narration: "But the squad's story was never just the scoreboard.",
        audioFocus: "voice",
      },
      {
        id: "beat-03",
        order: 3,
        momentId: "moment-round-seven",
        startMs: 522_340,
        endMs: 525_900,
        perspectiveId: "ace",
        transition: "match_cut",
        caption: "ACE'S VIEW",
        audioFocus: "voice",
      },
      {
        id: "beat-04",
        order: 4,
        momentId: "moment-smoke-save",
        startMs: 607_200,
        endMs: 611_500,
        perspectiveId: "rin",
        transition: "audio_lead",
        caption: "140 ms BEFORE THE SHOT",
        narration: "Rin had already saved Ace once.",
        audioFocus: "balanced",
      },
      {
        id: "beat-05",
        order: 5,
        momentId: "moment-unseen-hold",
        startMs: 681_800,
        endMs: 687_250,
        perspectiveId: "rin",
        transition: "split_screen",
        caption: "WHILE ACE ENTERED A…",
        narration: "In the final round, two enemies disappeared from Ace's story.",
        audioFocus: "voice",
      },
      {
        id: "beat-06",
        order: 6,
        momentId: "moment-unseen-hold",
        startMs: 689_200,
        endMs: 693_100,
        perspectiveId: "miko",
        transition: "audio_lead",
        caption: "LAST CHARGE GONE",
        narration: "Then Miko bought the final opening.",
        audioFocus: "voice",
      },
      {
        id: "beat-07",
        order: 7,
        momentId: "moment-unseen-hold",
        startMs: 694_100,
        endMs: 705_800,
        perspectiveId: "ace",
        transition: "match_cut",
        caption: "ONE PLAY · BUILT BY THREE",
        narration: "Ace finished a play the whole squad had authored.",
        audioFocus: "balanced",
      },
    ],
  },
  missedMoments: [
    {
      id: "missed-ace-flank",
      viewerId: "ace",
      momentId: "moment-unseen-hold",
      timestampMs: 684_900,
      headline: "Rin stopped two players behind you",
      explanation:
        "While you entered A, Rin held the entire flank alone. That delay removed the pressure behind your final 1v2.",
      revealedPerspectiveId: "rin",
      evidenceIds: ["ev-r13-rin-call", "ev-r13-rin-hold", "ev-r13-feed"],
    },
    {
      id: "missed-ace-miko",
      viewerId: "ace",
      momentId: "moment-unseen-hold",
      timestampMs: 689_200,
      headline: "Miko spent the defender's last utility",
      explanation:
        "Miko stepped into the crossfire and confirmed both charges were gone, creating the safe timing for your swing.",
      revealedPerspectiveId: "miko",
      evidenceIds: ["ev-r13-miko-draw", "ev-r13-miko-call"],
    },
    {
      id: "missed-rin-clutch",
      viewerId: "rin",
      momentId: "moment-unseen-hold",
      timestampMs: 694_100,
      headline: "Your delay became Ace's isolated 1v2",
      explanation:
        "After you fell, Ace used the extra seconds to take two separate fights instead of being pinched from behind.",
      revealedPerspectiveId: "ace",
      evidenceIds: ["ev-r13-rin-hold", "ev-r13-ace-clutch"],
    },
    {
      id: "missed-miko-flank",
      viewerId: "miko",
      momentId: "moment-unseen-hold",
      timestampMs: 684_900,
      headline: "Rin was fighting the rotation alone",
      explanation:
        "You heard Rin's short callout, but not the two-player hold happening off-screen while you cleared site.",
      revealedPerspectiveId: "rin",
      evidenceIds: ["ev-r13-flank-hud", "ev-r13-rin-call", "ev-r13-rin-hold"],
    },
  ],
  suggestedQuestions: [
    "What were my teammates doing during my final clutch?",
    "Why did everyone start laughing in round seven?",
    "Who first noticed the flank?",
    "Which action helped us secure the objective?",
    "Show me a moment I could not see from my perspective.",
    "Did anyone warn me before I pushed?",
    "What changed between our failed plan and the winning play?",
  ],
};

export function getParticipantName(
  session: UnseenSession,
  participantId: string | undefined,
): string | undefined {
  return session.participants.find((participant) => participant.id === participantId)
    ?.displayName;
}

export function formatSessionTimestamp(timestampMs: number): string {
  const totalSeconds = Math.max(0, Math.floor(timestampMs / 1000));
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}:${seconds.toString().padStart(2, "0")}`;
}
